name: Build and Publish

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

env:
  MAJOR: '1'
  MINOR: '0'
  VERSION: '1.0.${{ github.run_number }}'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Restore dependencies
      run: dotnet restore --no-cache --force-evaluate
      
    - name: Run tests
      run: dotnet test Observability.sln --configuration Release --no-restore
      
    - name: Pack NuGet packages
      run: |
        dotnet pack Alerting/Alerting.csproj --configuration Release --no-restore --output packages /p:Version=${{ env.VERSION }}
        dotnet pack Logging.Serilog/Logging.Serilog.csproj --configuration Release --no-restore --output packages /p:Version=${{ env.VERSION }}
        dotnet pack Logging.Serilog.ApplicationInsights/Logging.Serilog.ApplicationInsights.csproj --configuration Release --no-restore --output packages /p:Version=${{ env.VERSION }}
        dotnet pack Logging.TestingUtilities/Logging.TestingUtilities.csproj --configuration Release --no-restore --output packages /p:Version=${{ env.VERSION }}
        dotnet pack Logging.Serilog.AspNet/Logging.Serilog.AspNet.csproj --configuration Release --no-restore --output packages /p:Version=${{ env.VERSION }}

    - name: Push NuGet packages
      run: dotnet nuget push "packages/*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ github.token }} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}